name: Build Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install app dependencies
        run: |
          cd release/app
          npm install
          cd ../..
        
      - name: Build application
        run: npm run build
        
      - name: Package for Windows
        run: npx electron-builder build --win --x64 --publish never
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: release/build/*.exe

